server:
    port: 8084  # Tomcat default port


spring:
    kafka:
        consumer:
            bootstrap-servers: kafka:9092
            group-id: betPlatform
            auto-offset-reset: earliest
        producer:
            bootstrap-servers: kafka:9092

        bank-response: bet.bank-response
        reserve-bid: bet.reserve-bid
        two-factor: bet.two-factor-customer
        two-factor-success: bet.two-factor-customer-success
        payment-request: bet.payment-request
        camunda: (camunda) | (camunda.*)

zeebe:
    client:
        broker:
            gateway-address: zeebe:26500
        security:
            plaintext: true
