server:
    port: 8095  # Tomcat default port


spring:
    kafka:
        consumer:
            bootstrap-servers: kafka:9092
            group-id: betPlatform
            auto-offset-reset: earliest
        producer:
            bootstrap-servers: kafka:9092


