server:
    port: 8082  # Tomcat default port


spring:
    kafka:
        consumer:
            bootstrap-servers: kafka:9092
            group-id: betPlatform
            auto-offset-reset: earliest
        producer:
            bootstrap-servers: kafka:9092

        game:
            game-topic-published: game.published
            game-topic-started: game.started
            game-topic-ended: game.ended
            game-topic-ended-camunda: camunda.game.ended
        contract:
            contract-requested: camunda.contract.requested
            contract-rejected: camunda.contract.rejected
            contract-accepted: camunda.contract.accepted
        bet:
            bet-requested: camunda.bet.requested.camunda
            bet-rejected: camunda.bet.rejected
            bet-accepted: camunda.bet.accepted




