server:
    port: 8082  # Tomcat default port


spring:
    kafka:
        consumer:
            bootstrap-servers: kafka:9092
            group-id: betPlatform
            auto-offset-reset: earliest
        producer:
            bootstrap-servers: kafka:9092

        game-topic: bet.game-topic
        bank-response: bet.bank-response
        bad-bank-response: bet.bad-bank-response
        reserve-bid: bet.reserve-bid

camunda.bpm:
    admin-user:
        id: demo
        password: demo
    filter.create: All Tasks
    deployment-resource-pattern:
        - classpath*:**/*.bpmn
        - classpath*:**/*.bpmn20.xml
        - classpath*:**/*.dmn
        - classpath*:**/*.dmn11.xml
        - classpath*:**/*.form
