server:
    port: 8081  # Tomcat default port


spring:
    kafka:
        consumer:
            bootstrap-servers: kafka:9092
            group-id: betPlatform
            auto-offset-reset: earliest
        producer:
            bootstrap-servers: kafka:9092

        user:
            request: user.check-request
            result: camunda.user.check-result
        freeze:
            request: bank.freeze-request
            result: camunda.freeze-result



