server:
    port: 8081  # Tomcat default port


spring:
    kafka:
        consumer:
            bootstrap-servers: kafka:9092
            group-id: betPlatform
            auto-offset-reset: earliest
        producer:
            bootstrap-servers: kafka:9092

        bank-response: bet.bank-response
        reserve-bid: bet.reserve-bid



camunda.bpm:
    admin-user:
        id: demo
        password: demo
    filter.create: All Tasks