server:
    port: 8083  # Tomcat default port

baseuri: http://localhost:8083


spring:
    kafka:
        consumer:
            bootstrap-servers: kafka:9092
            group-id: myGroup
            auto-offset-reset: earliest
            key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
            value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        producer:
            bootstrap-servers: kafka:9092
            key-serializer: org.apache.kafka.common.serialization.StringSerializer
            value-serializer: org.apache.kafka.common.serialization.StringSerializer

        game-topic-published: game.published
        game-topic-started: camunda.game.started
        game-topic-ended: camunda.game.started